#This is TNFSH absent query Bot Main Program
#gnsJhenJie 2020 Copyright
#Author: gnsJhenJie (github.com/gnsJhenJie)

import os
import io
import sys
import json
from datetime import datetime, timedelta, date
import requests
from flask import Flask, request
import time
import pandas
import socket
import random
import pyshorteners
from pyshorteners import Shorteners  
#Dymanic link 縮網址套件
from python_firebase_url_shortener.url_shortener import UrlShortener
#Put your Firebase API Key below. Using system variable is recommended.
#放置你的Firebase API Key 在下方 建議改用環境變數
firebase_api_key = 'FIREBASE_API_KEY'
url_shortener = UrlShortener(firebase_api_key, 'tfabsent')

#firebase:
# 引用firebase必要套件
# import firebase packages
import firebase
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore
# Attach Firebase json credentials by PATH
# 引用私密金鑰 Firebase json credentials
# path/to/serviceAccount.json 請用自己存放的路徑
cred = credentials.Certificate('PATH')
# 初始化firebase，注意不能重複初始化
firebase_admin.initialize_app(cred)
# 初始化firestore
db = firestore.client()
# firebase Firestore Variables
# firebase firestore 參數
user_info_collection_name = "user_info"
user_info_path = "user_info"
user_info_collection_ref = db.collection(user_info_path)

total_list_collection_name = 'total_list'
total_list_collection_path = 'total_list'
total_list_collection_ref = db.collection(total_list_collection_path)

transfer_name = 'transfer'
transfer_path = 'transfer'
transfer_ref = db.collection(transfer_path)

#Crawl web packages
import urllib.request, urllib.parse, urllib.error
from bs4 import BeautifulSoup
# Import Google Application Credentials json by PATH
# 導入Google Application Credentials json檔的檔案路徑
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="PATH"


app = Flask(__name__)

@app.route('/', methods=['GET'])
def verify():
    # when the endpoint is registered as a webhook, it must echo back
    # the 'hub.challenge' value it receives in the query arguments
    # Verify Token is generated by Facebook Please set it to environmental variable
    # Verify Token 為Facebook提供的Token 請將其設為環境變數
    if request.args.get("hub.mode") == "subscribe" and request.args.get("hub.challenge"):
        if not request.args.get("hub.verify_token") == os.environ["VERIFY_TOKEN"]:
            return "Verification token mismatch", 403
        return request.args["hub.challenge"], 200

    return "Hello world", 200


@app.route('/', methods=['POST'])
def webhook():

    # endpoint for processing incoming messaging events
    # 處理流入訊息

    data = request.get_json()
    log(data)  # you may not want to log every incoming message in production, but it's good for testing 

    if data["object"] == "page":

        for entry in data["entry"]:
            for messaging_event in entry["messaging"]:

                if messaging_event.get("message"):  # someone sent us a message 某人發送了訊息
                    is_text = False
                    sender_id = messaging_event["sender"]["id"]        # the facebook ID of the person sending you the message 傳送者Facebook ID
                    try:  #Check if it is a text message... 判斷是否為文字訊息
                        message_text = messaging_event["message"]["text"]  # the message's text 訊息文字部分
                        is_text = True
                    except:
                        message_text = 'QAQ' # If the message is not based on text (sticker, audio, image, etc) 若非文字訊息 (貼圖,音檔,圖像...)
                        is_text = False
                    is_member_ed = bool()
                    try:  #Check if it is a member, if true record its info 嘗試擷取資料庫中的資訊
                        doc_ref = user_info_collection_ref.document(sender_id)
                        docs = doc_ref.get()
                        docdict = docs.to_dict()
                        tnfsh_class = format(docdict['tnfsh_class'])
                        tnfsh_number = format(docdict['tnfsh_number'])
                        Created_time = format(docdict['Created_time'])
                        nickname = format(docdict['nickname'])
                        PS = format(docdict['PS'])
                        Last_changed_time = format(docdict['Last_changed_time'])
                        fb_name = format(docdict['fb_name'])
                        fb_first_name = format(docdict['fb_first_name'])
                        fb_last_name = format(docdict['fb_last_name'])
                        pss_win = format(docdict['pss_win'])
                        pss_lose = format(docdict['pss_lose'])
                        pss_draw = format(docdict['pss_draw'])
                        is_member_ed = True
                    except:  #Not a member 非會員
                        is_member_ed = False 
                        
                    if is_member_ed and is_text:
                        msg = message_text.lower().replace("^","**",3).replace("＋","+",10).replace("－","-",10).replace('＊','*',10).replace('／','/',10).replace('（','(',6).replace('）',')',6).replace('÷','/',5).replace('×','*',5)
                        if msg == 'hi':
                            radm = random.randint(1,2)
                            if radm == 1:
                                message_to_send = "Hi, " + nickname
                            elif radm == 2:
                                message_to_send = "Hello, " + nickname
                        elif msg == 'q' or msg == '查詢最近缺席' or msg == '查訊最近缺席':  #query these 2 days 
                            date_today = datetime.now().date().strftime("%Y-%m-%d")
                            date_p1 = (datetime.now() + timedelta(days = -1)).strftime("%Y-%m-%d")
                            date_p2 = (datetime.now() + timedelta(days = -2)).strftime("%Y-%m-%d")
                            #Check today 檢查今日缺席
                            count_absent_today, count_late_today, count_leave_today = absent_query(tnfsh_class, tnfsh_number, date_today)
                            #Check p1 day 檢查昨日缺席
                            count_absent_p1, count_late_p1, count_leave_p1 = absent_query(tnfsh_class, tnfsh_number, date_p1)
                            #Check p2 day 檢查前天缺席
                            count_absent_p2, count_late_p2, count_leave_p2 = absent_query(tnfsh_class, tnfsh_number, date_p2)
                            #Deal message_to_send
                            message_to_send = '<您的最近缺席>\n'
                            if count_absent_today == 0:
                                message_to_send += '查無本日缺席\n'
                            else:
                                message_to_send += '你今天共缺席'+str(count_absent_today)+'節課\n'
                            if count_late_today > 0:
                                message_to_send += '你今天共遲到'+str(count_late_today)+'節課\n'
                            if count_leave_today > 0:
                                message_to_send += '你今天共早退'+str(count_leave_today)+'節課\n'
                            if count_absent_p1 == 0:
                                message_to_send += '查無昨天缺席\n'
                            else:
                                message_to_send += '你昨天共缺席'+str(count_absent_p1)+'節課\n'
                            if count_late_p1 > 0:
                                message_to_send += '你昨天共遲到'+str(count_late_p1)+'節課\n'
                            if count_leave_p1 >0:
                                message_to_send += '你昨天共早退'+str(count_leave_p1)+'節課\n'
                            if count_absent_p2 == 0:
                                message_to_send += '查無前天缺席\n'
                            else:
                                message_to_send += '你前天共缺席'+str(count_absent_p2)+'節課\n'
                            if count_late_p2 > 0:
                                message_to_send += '你前天共遲到'+str(count_late_p2)+'節課\n'
                            if count_leave_p2 > 0:
                                message_to_send += '你前天共早退'+str(count_leave_p2)+'節課\n'
                            if count_absent_today + count_late_today + count_leave_today + count_absent_p1 + count_late_p1 + count_leave_p1 + count_absent_p2 + count_late_p2 + count_leave_p2 >0 :
                                message_to_send += '快去看看哪節課被記吧!\n'
                                message_to_send += shorten_url('https://sp.tnfsh.tn.edu.tw/attend/index.php/attend/search?begin='+date_p2+'&end='+date_today+'&class='+tnfsh_class+'&num='+tnfsh_number)
                        elif msg == 'qw' or msg == '查詢本週缺席':
                            weekday = date.today().isoweekday()   
                            count_absent_total, count_late_total, count_leave_total = absent_query_period(tnfsh_class, tnfsh_number, (datetime.now() + timedelta(days = -weekday+1)).strftime("%Y-%m-%d"), datetime.now().date().strftime("%Y-%m-%d"))                            
                            message_to_send = '<您的本週缺席>\n'
                            if count_absent_total == 0:
                                message_to_send += '查無本週缺席\n'
                            else:
                                message_to_send += '本週共缺席'+str(count_absent_total)+'節\n'
                            if count_late_total > 0:
                                message_to_send += '本週共遲到'+str(count_late_total)+'節\n'
                            if count_leave_total > 0:
                                message_to_send += '本周共早退'+str(count_leave_total)+'節\n'
                            if count_absent_total + count_late_total + count_leave_total > 0:
                                message_to_send += '快去看看哪節課被記吧!\n'
                                message_to_send += shorten_url('https://sp.tnfsh.tn.edu.tw/attend/index.php/attend/search?begin='+(datetime.now() + timedelta(days = -weekday+1)).strftime("%Y-%m-%d")+'&end='+datetime.now().date().strftime("%Y-%m-%d")+'&class='+tnfsh_class+'&num='+tnfsh_number)
                        elif msg[0] == 'q' and len(msg) == 17: #Query for specific date 查詢指定區間缺席
                            legal = False
                            try:
                             if  2101 > int(msg[1:5]) > 1999 and 13 > int(msg[5:7]) > 0 and 32 > int(msg[7:9]) > 0 and 2101 > int(msg[9:13]) > 1999 and int(msg[9:13]) >= int(msg[1:5]) and 13 > int(msg[13:15]) > 0 and 32 > int(msg[15:17]) > 0:
                                legal = True
                            except:
                                legal = False
                            if legal == True:
                                count_absent_total, count_late_total, count_leave_total = absent_query_period(tnfsh_class, tnfsh_number, msg[1:5] + '-' + msg[5:7] + '-' + msg[7:9] , msg[9:13] + '-' + msg[13:15] + '-' + msg[15:17])                            
                                message_to_send = '<查詢指定區間>\n'
                                if count_absent_total == 0:
                                    message_to_send += '查無本區間缺席\n'
                                else:
                                    message_to_send += '本區間共缺席'+str(count_absent_total)+'節\n'
                                if count_late_total > 0:
                                    message_to_send += '本區間遲到'+str(count_late_total)+'節\n'
                                if count_leave_total > 0:
                                    message_to_send += '本區間共早退'+str(count_leave_total)+'節\n'
                                if count_absent_total + count_late_total + count_leave_total > 0:
                                    message_to_send += '快去看看哪節課被記吧!\n'
                                    message_to_send += shorten_url('https://sp.tnfsh.tn.edu.tw/attend/index.php/attend/search?begin='+msg[1:5] + '-' + msg[5:7] + '-' + msg[7:9]+'&end='+msg[9:13] + '-' + msg[13:15] + '-' + msg[15:17]+'&class='+tnfsh_class+'&num='+tnfsh_number)
                                send_message(sender_id, message_to_send)
                                message_to_send = 'Btw, 請確認一下你輸入的日期是不是都是這個班級座號~~'
                            else:
                                pass
                        elif msg == 'help':
                            message_to_send = '查詢近三日缺席: q 或 查詢最近\n查詢本周缺席: qw 或 查詢本週\n重設班級座號: c班級座號 (e.g. c10101)\n設定暱稱:ni+暱稱 (e.g. ni天堂)\n查詢個人設定:profile\n顯示課表:course'
                            send_message(sender_id,message_to_send)
                            message_to_send = '查詢指定區間: q+起始結束西元年月日\n(e.g. q2018010120190331)\n設定星期幾要推播晚安訊息:\nset+收推播的星期幾\n(e.g. 星期二四六日 set2467git)\n關閉提醒:set0'
                            send_message(sender_id, message_to_send)
                            message_to_send = '也可以跟我say hi ㄛ~~'
                            send_message(sender_id, message_to_send)
                            message_to_send = '像是1+1之類簡單的數學我其實也會算!\n想跟我玩遊戲的話就輸入gamehelp吧!'
                        elif msg == 'gamehelp' or msg == 'game help':
                            message_to_send = '想跟我玩剪刀石頭布的話就直接出拳喔!\n查看對決紀錄輸入:剪刀石頭布 或 pss report'
                        elif msg == 'course' or msg == "我的課表" or msg == "課表":
                            message_to_send = ""
                            send_image_message(sender_id, "https://tnfsh-absentee.web.app/courseTables/"+tnfsh_class+".jpeg")
                        elif msg == '剪刀' or msg == 'scissors' or msg == u'✂️' or msg == u'✌️' or msg == u'✌🏻' or msg == u'✌🏼' or msg == u'✌🏽' or msg == u'✌🏾' or msg == u'✌🏿':
                            radm = random.randint(1,10)
                            if radm <=3:
                                radmm = random.randint(1,5)
                                if radmm == 1:
                                    message_to_send = '我出剪刀!\n平手~'
                                elif radmm == 2:
                                    message_to_send = '剪刀!'
                                    send_message(sender_id,message_to_send)
                                    message_to_send = '平手OuO'
                                elif radm == 3:
                                    message_to_send = '剪刀:Scissors~\n平手:Draw~'
                                else:
                                    message_to_send = '小鸚鵡出....剪刀!'
                                    send_message(sender_id,message_to_send)
                                    message_to_send = "平手!"
                                pss_draw = str(int(pss_draw)+1)
                            elif radm<=8:
                                radmm = random.randint(1,5)
                                if radmm == 1:
                                    message_to_send = '石頭~~\n啦啦啦~我贏啦~'
                                elif radmm == 2:
                                    message_to_send = 'Stone!'
                                    send_message(sender_id,message_to_send)
                                    message_to_send = 'You are too VEGETABLE.'
                                elif radmm == 3:
                                    message_to_send = '小鸚鵡出石頭~~'
                                elif radmm == 4:
                                    message_to_send = 'ㄏ~石頭!贏啦!'
                                elif radmm == 5:
                                    message_to_send = '嫩!小鸚鵡都比你會玩~\n我出石頭你輸啦!'
                                pss_lose = str(int(pss_lose)+1)
                            else:
                                radmm = random.randint(1,5)
                                if radmm == 1:
                                    message_to_send = '布!你贏啦!\n算你厲害'
                                elif radmm == 2:
                                    message_to_send = '我出布!\n...小鸚鵡輸了QQ'
                                elif radmm == 3:
                                    message_to_send = 'Paper!幫你加1分'
                                elif radmm == 4:
                                    message_to_send = '小鸚鵡出布!恭喜你贏惹。'
                                elif radmm == 5:
                                    message_to_send = '布!不!我輸了'
                                pss_win = str(int(pss_win)+1)
                            new_record = dict()
                            new_record['tnfsh_class'] = tnfsh_class
                            new_record['tnfsh_number'] = tnfsh_number
                            new_record['fb_sender_id'] = sender_id
                            new_record['Created_time'] = Created_time
                            new_record['Last_changed_time'] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                            new_record['nickname'] = nickname
                            new_record['PS'] = PS
                            new_record['fb_name'] = fb_name
                            new_record['fb_last_name'] = fb_last_name
                            new_record['fb_first_name'] = fb_first_name
                            new_record['pss_win'] = pss_win
                            new_record['pss_lose'] = pss_lose
                            new_record['pss_draw'] = pss_draw
                            doc_ref = db.collection("user_info").document(sender_id)
                            doc_ref.set(new_record)
                        elif msg == '石頭' or msg == 'stone' or msg == u'✊' or msg == u'✊🏻' or msg == u'✊🏼' or msg == u'✊🏽' or msg == u'✊🏾' or msg == u'✊🏿':
                            t = datetime.now().second
                            radm = random.randint(1,t+2)
                            if radm <=17:
                                radmm = random.randint(1,5)
                                if radmm == 1:
                                    message_to_send = '我出剪刀!\nSo sad..'
                                elif radmm == 2:
                                    message_to_send = '剪刀!'
                                    send_message(sender_id,message_to_send)
                                    message_to_send = '難過@@'
                                elif radmm == 3:
                                    message_to_send = '剪刀:Scissors~\n輸了:Lose...'
                                elif radmm == 4:
                                    message_to_send = '輸了QQ\n我出剪刀...'
                                else:
                                    message_to_send = '小鸚鵡出....剪刀!'
                                    send_message(sender_id,message_to_send)
                                    message_to_send = "算你厲害!"
                                pss_win = str(int(pss_win)+1)
                            elif radm<=24:
                                radmm = random.randint(1,5)
                                if radmm == 1:
                                    message_to_send = '石頭~~\n平手ㄏㄏ'
                                elif radmm == 2:
                                    message_to_send = 'Stone!'
                                    send_message(sender_id,message_to_send)
                                    message_to_send = '~Draw~'
                                elif radmm == 3:
                                    message_to_send = '小鸚鵡出石頭~~'
                                elif radmm == 4:
                                    message_to_send = '石頭!平手~\n阿不就好棒棒!'
                                elif radmm == 5:
                                    message_to_send = '小鸚鵡出石頭~~\n再來一次啊!!'
                                pss_draw = str(int(pss_draw)+1)
                            else:
                                radmm = random.randint(1,5)
                                if radmm == 1:
                                    message_to_send = '布!你輸啦!\n算小鸚鵡厲害'
                                elif radmm == 2:
                                    message_to_send = '我出布!\n...小鸚鵡贏了'
                                elif radmm == 3:
                                    message_to_send = 'Paper!嫩!'
                                elif radmm == 4:
                                    message_to_send = '小鸚鵡出布!恭喜你輸惹~~'
                                elif radmm == 5:
                                    message_to_send = '布!你輸了哈哈~'
                                pss_lose = str(int(pss_lose)+1)
                            new_record = dict()
                            new_record['tnfsh_class'] = tnfsh_class
                            new_record['tnfsh_number'] = tnfsh_number
                            new_record['fb_sender_id'] = sender_id
                            new_record['Created_time'] = Created_time
                            new_record['Last_changed_time'] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                            new_record['nickname'] = nickname
                            new_record['PS'] = PS
                            new_record['fb_name'] = fb_name
                            new_record['fb_last_name'] = fb_last_name
                            new_record['fb_first_name'] = fb_first_name
                            new_record['pss_win'] = pss_win
                            new_record['pss_lose'] = pss_lose
                            new_record['pss_draw'] = pss_draw
                            doc_ref = db.collection("user_info").document(sender_id)
                            doc_ref.set(new_record)
                        elif msg == '布' or msg == 'paper' or msg == u'🖐' or msg == u'🖐🏻' or msg == u'🖐🏼' or msg == u'🖐🏽' or msg == u'🖐🏾' or msg == u'🖐🏿' or msg == u'🤚' or msg == u'🤚🏻' or msg == u'🤚🏼' or msg == u'🤚🏽' or msg == u'🤚🏾' or msg == u'🤚🏿' or msg == u'✋' or msg == u'✋🏻' or msg == u'✋🏼' or msg == u'✋🏽' or msg == u'✋🏾' or msg == u'✋🏿':
                            t = datetime.now().second
                            radm = random.randint(1,t+2)
                            if radm <=13:
                                radmm = random.randint(1,5)
                                if radmm == 1:
                                    message_to_send = '我出剪刀!\nHappy!'
                                elif radmm == 2:
                                    message_to_send = '剪刀!'
                                    send_message(sender_id,message_to_send)
                                    message_to_send = 'Ya!'
                                elif radmm == 3:
                                    message_to_send = '剪刀:Scissors~\n贏了:Win...'
                                elif radmm == 4:
                                    message_to_send = '我出剪刀ㄏㄏ'
                                else:
                                    message_to_send = '小鸚鵡出....剪刀!'
                                    send_message(sender_id,message_to_send)
                                    message_to_send = "菜雞!"
                                pss_lose = str(int(pss_lose)+1)
                            elif radm<=29:
                                radmm = random.randint(1,5)
                                if radmm == 1:
                                    message_to_send = '石頭~~\n都欺負小鸚鵡啊...'
                                elif radmm == 2:
                                    message_to_send = 'Stone!'
                                    send_message(sender_id,message_to_send)
                                    message_to_send = '小鸚鵡難過...'
                                elif radmm == 3:
                                    message_to_send = '小鸚鵡出石頭~~'
                                elif radmm == 4:
                                    message_to_send = '石頭!\n阿不就好棒棒!'
                                elif radmm == 5:
                                    message_to_send = '小鸚鵡出石頭~~\n再來一次啊!!'
                                pss_win = str(int(pss_win)+1)
                            else:
                                radmm = random.randint(1,5)
                                if radmm == 1:
                                    message_to_send = '布!平手辣!'
                                elif radmm == 2:
                                    message_to_send = '我出Paper\nDraw!'
                                elif radmm == 3:
                                    message_to_send = 'Paper!哼!'
                                elif radmm == 4:
                                    message_to_send = '小鸚鵡出布呦!'
                                elif radmm == 5:
                                    message_to_send = 'P-a-p-p-e-r!平手OuO'
                                pss_draw = str(int(pss_draw)+1)
                            new_record = dict()
                            new_record['tnfsh_class'] = tnfsh_class
                            new_record['tnfsh_number'] = tnfsh_number
                            new_record['fb_sender_id'] = sender_id
                            new_record['Created_time'] = Created_time
                            new_record['Last_changed_time'] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                            new_record['nickname'] = nickname
                            new_record['PS'] = PS
                            new_record['fb_name'] = fb_name
                            new_record['fb_last_name'] = fb_last_name
                            new_record['fb_first_name'] = fb_first_name
                            new_record['pss_win'] = pss_win
                            new_record['pss_lose'] = pss_lose
                            new_record['pss_draw'] = pss_draw
                            doc_ref = db.collection("user_info").document(sender_id)
                            doc_ref.set(new_record)
                        elif msg == '剪刀石頭布' or msg == 'paper scissors stone' or msg == 'pss report':
                            win_rate = round(int(pss_win)/(int(pss_win)+int(pss_lose)+0.0000000000001),2)
                            message_to_send = '<剪刀石頭布紀錄>\n贏我:'+pss_win+'次\n輸我:'+pss_lose+'次\n平手:'+pss_draw+'次\n勝率:'+str(win_rate)+'\n'
                            if win_rate < 0.3:
                                radm = random.randint(1,4)
                                if radm == 1:
                                    message_to_send += '小鸚鵡覺得你超嫩!'
                                elif radm == 2:
                                    message_to_send += '慘不忍睹啊~'
                                elif radm == 3:
                                    message_to_send += '菜雞出現!ㄘㄞˋㄐㄧ'
                                else:
                                    message_to_send += '小鸚鵡瘋狂贏你欸!'
                            elif win_rate < 0.45:
                                radm = random.randint(1,3)
                                if radm == 1:
                                    mesage_to_send += '還行~還行~'
                                elif radm == 2:
                                    message_to_send += '普普通通'
                                else:
                                    message_to_send += '你比小鸚鵡爛一點ㄏㄏ'
                            elif win_rate < 0.77:
                                radm = random.randint(1,4)
                                if radm == 1:
                                    message_to_send += '好像很強欸!'
                                elif radm == 2:
                                    message_to_send += '小鸚鵡把你當對手囉!'
                                elif radm == 3:
                                    message_to_send += '馬上就要被我打趴ㄌ'
                                elif radm == 4:
                                    message_to_send += '小鸚鵡覺得你有點厲害ㄟ'
                            elif win_rate < 0.9:
                                radm = random.randint(1,4)
                                if radm == 1:
                                    message_to_send += '大師!'
                                elif radm == 2:
                                    message_to_send += '小鸚鵡甘拜下風...'
                                elif radm == 3:
                                    message_to_send += '小鸚鵡覺得你超厲害'
                                else:
                                    message_to_send += '太強了吧!!!'
                            else:
                                radm = random.randint(1,4)
                                if radm == 1:
                                    message_to_send += '好景不常的'
                                elif radm == 2:
                                    message_to_send += '根本大神來著!'
                                elif radm == 3:
                                    message_to_send += '你是不是看透小鸚鵡的心了...'
                                elif radm == 4:
                                    message_to_send += '小鸚鵡拜你為師~'
                        elif msg[0] == 'c' and len(msg) == 6:  #Change class and number 更改班級座號
                            try:
                                check_is_number = int(message_text[1:6])
                                
                                if 32000>int(check_is_number)>10099 or int(check_is_number)==66666:

                                    tnfsh_class = message_text[1:4]
                                    tnfsh_number = message_text[4:6]

                                    new_record = dict()
                                    new_record['tnfsh_class'] = tnfsh_class
                                    new_record['tnfsh_number'] = tnfsh_number
                                    new_record['fb_sender_id'] = sender_id
                                    new_record['Created_time'] = Created_time
                                    new_record['Last_changed_time'] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                                    new_record['nickname'] = nickname
                                    new_record['PS'] = PS
                                    new_record['category'] = category
                                    new_record['student_ID'] = student_ID
                                    new_record['true_name'] = true_name
                                    new_record['fb_name'] = fb_name
                                    new_record['fb_profile_pic'] = fb_profile_pic
                                    new_record['fb_last_name'] = fb_last_name
                                    new_record['fb_first_name'] = fb_first_name
                                    new_record['pss_win'] = pss_win
                                    new_record['pss_lose'] = pss_lose
                                    new_record['pss_draw'] = pss_draw
                                    #Sol 1
                                    doc_ref = db.collection("user_info").document(sender_id)
                                    #Sol 2
                                    #doc_path = "/pyradise_students/"+fb_sender_id
                                    #doc_ref = db.document(doc_path)
                                    doc_ref.set(new_record)
                                    message_to_send = tnfsh_class+tnfsh_number+"已完成更改"
                            except:
                                message_to_send = 'OAO'
                        elif msg[0:2] == 'ni' and len(message_text) > 2 and message_text[2] != ' ': #Change nickname 更改暱稱
                            if len(msg)<1903:
                                new_record = dict()
                                new_record['tnfsh_class'] = tnfsh_class
                                new_record['tnfsh_number'] = tnfsh_number
                                new_record['fb_sender_id'] = sender_id
                                new_record['Created_time'] = Created_time
                                new_record['Last_changed_time'] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                                new_record['nickname'] = message_text[2:]
                                new_record['PS'] = PS
                                new_record['fb_name'] = fb_name
                                new_record['fb_last_name'] = fb_last_name
                                new_record['fb_first_name'] = fb_first_name
                                new_record['pss_win'] = pss_win
                                new_record['pss_lose'] = pss_lose
                                new_record['pss_draw'] = pss_draw
                                #Sol 1
                                doc_ref = db.collection("user_info").document(sender_id)
                                #Sol 2
                                #doc_path = "/pyradise_students/"+fb_sender_id
                                #doc_ref = db.document(doc_path)
                                doc_ref.set(new_record)
                                message_to_send = message_text[2:]+"已完成更改"
                            else:
                                message_to_send = '名字太長囉~(最多1900字)'
                        elif msg[0:3] == 'set' and 3 < len(msg) < 11 and (msg.find('1') != -1 or msg.find('2') != -1 or msg.find('3') != -1 or msg.find('4') != -1 or msg.find('5') != -1 or msg.find('6') != -1 or msg.find('7') != -1 or msg.find('0')!=-1): #設定星期幾廣播
                            message_to_send = '處理中...'
                            send_message(sender_id, message_to_send)
                            #Add to total_list
                            total_list_doc_ref = db.collection("total_list").document('total1')
                            total_docs = total_list_doc_ref.get()
                            fb_sender_id_list = format(total_docs.to_dict()['fb_sender_id_list'])
                            fb_sender_id_list_week1 = format(total_docs.to_dict()['fb_sender_id_list_week1'])
                            fb_sender_id_list_week2 = format(total_docs.to_dict()['fb_sender_id_list_week2'])
                            fb_sender_id_list_week3 = format(total_docs.to_dict()['fb_sender_id_list_week3'])
                            fb_sender_id_list_week4 = format(total_docs.to_dict()['fb_sender_id_list_week4'])
                            fb_sender_id_list_week5 = format(total_docs.to_dict()['fb_sender_id_list_week5'])
                            fb_sender_id_list_week6 = format(total_docs.to_dict()['fb_sender_id_list_week6'])
                            fb_sender_id_list_week7 = format(total_docs.to_dict()['fb_sender_id_list_week7'])
                            if msg.find('1') == -1: #set指令中沒有1
                                fb_sender_id_list_week1 = fb_sender_id_list_week1.replace(','+sender_id,'')
                            else: #set指令中有1
                                if fb_sender_id_list_week1.find(sender_id) == -1: #本來這天沒有要廣播ㄌ #如果本來有要廣播就不動
                                    fb_sender_id_list_week1 = fb_sender_id_list_week1 + ',' + sender_id
                            if msg.find('2') == -1: #set指令中沒有2
                                fb_sender_id_list_week2 = fb_sender_id_list_week2.replace(','+sender_id,'')
                            else:
                                if fb_sender_id_list_week2.find(sender_id) == -1: #本來這天沒有要廣播ㄌ #如果本來有要廣播就不動
                                    fb_sender_id_list_week2 = fb_sender_id_list_week2 + ',' + sender_id
                            if msg.find('3') == -1: #set指令中沒有3
                                fb_sender_id_list_week3 = fb_sender_id_list_week3.replace(','+sender_id,'')
                            else:
                                if fb_sender_id_list_week3.find(sender_id) == -1: #本來這天沒有要廣播ㄌ #如果本來有要廣播就不動
                                    fb_sender_id_list_week3 = fb_sender_id_list_week3 + ',' + sender_id
                            if msg.find('4') == -1: #set指令中沒有4
                                fb_sender_id_list_week4 = fb_sender_id_list_week4.replace(','+sender_id,'')
                            else:
                                if fb_sender_id_list_week4.find(sender_id) == -1: #本來這天沒有要廣播ㄌ #如果本來有要廣播就不動
                                    fb_sender_id_list_week4 = fb_sender_id_list_week4 + ',' + sender_id
                            if msg.find('5') == -1: #set指令中沒有5
                                fb_sender_id_list_week5 = fb_sender_id_list_week5.replace(','+sender_id,'')
                            else:
                                if fb_sender_id_list_week5.find(sender_id) == -1: #本來這天沒有要廣播ㄌ #如果本來有要廣播就不動
                                    fb_sender_id_list_week5 = fb_sender_id_list_week5 + ',' + sender_id
                            if msg.find('6') == -1: #set指令中沒有6
                                fb_sender_id_list_week6 = fb_sender_id_list_week6.replace(','+sender_id,'')
                            else:
                                if fb_sender_id_list_week6.find(sender_id) == -1: #本來這天沒有要廣播ㄌ #如果本來有要廣播就不動
                                    fb_sender_id_list_week6 = fb_sender_id_list_week6 + ',' + sender_id
                            if msg.find('7') == -1: #set指令中沒有7
                                fb_sender_id_list_week7 = fb_sender_id_list_week7.replace(','+sender_id,'')
                            else:
                                if fb_sender_id_list_week7.find(sender_id) == -1: #本來這天沒有要廣播ㄌ #如果本來有要廣播就不動
                                    fb_sender_id_list_week7 = fb_sender_id_list_week7 + ',' + sender_id
                            total_list_new_record = dict()
                            total_list_new_record['fb_sender_id_list'] = fb_sender_id_list
                            total_list_new_record['fb_sender_id_list_week1'] = fb_sender_id_list_week1
                            total_list_new_record['fb_sender_id_list_week2'] = fb_sender_id_list_week2
                            total_list_new_record['fb_sender_id_list_week3'] = fb_sender_id_list_week3
                            total_list_new_record['fb_sender_id_list_week4'] = fb_sender_id_list_week4
                            total_list_new_record['fb_sender_id_list_week5'] = fb_sender_id_list_week5
                            total_list_new_record['fb_sender_id_list_week6'] = fb_sender_id_list_week6
                            total_list_new_record['fb_sender_id_list_week7'] = fb_sender_id_list_week7
                            total_list_doc_ref.set(total_list_new_record)
                            message_to_send = msg + '設定完成'
                        elif msg.find('profile') != -1: # Check profile 查詢個人設定
                            message_to_send = '<個人設定檔>\n暱稱: ' + nickname + '\n班級: ' + tnfsh_class + '\n座號: ' + tnfsh_number
                        elif (msg.find('*') != -1 or msg.find('/') != -1) and len(msg) < 12 and msg.find('**') == -1: #Easy Calculator 簡單的計算機
                            try:
                                radm = random.randint(1,3)
                                if radm == 1:
                                    message_to_send = '應該是... ' + str(eval(msg)) + '吧!'
                                elif radm == 2:
                                    message_to_send = str(eval(msg)) + '\n聰明吧!'
                                elif radm == 3:
                                    message_to_send = str(eval(msg))
                            except:
                                pass
                        elif msg.find('**') != -1 and len(msg) < 5:
                            try:
                                radm = random.randint(1,3)
                                if radm == 1:
                                    message_to_send = '應該是... ' + str(eval(msg)) + '吧!'
                                elif radm == 2:
                                    message_to_send = str(eval(msg)) + '\n聰明吧!'
                                elif radm == 3:
                                    message_to_send = str(eval(msg))
                            except:
                                pass
                        elif (msg.find('+') != -1 or msg.find('-') != -1) and len(msg) < 21:
                            try:
                                radm = random.randint(1,3)
                                if radm == 1:
                                    message_to_send = '應該是... ' + str(eval(msg)) + '吧!'
                                elif radm == 2:
                                    message_to_send = str(eval(msg)) + '\n聰明吧!'
                                elif radm == 3:
                                    message_to_send = str(eval(msg))
                            except:
                                pass                      
                        elif msg.find('小鸚鵡') != -1:
                            radm = random.randint(1,5)
                            if radm == 1:
                                message_to_send = '小鸚鵡在此為您服務!'
                            elif radm == 2:
                                message_to_send = '讚辣!'
                            elif radm == 3:
                                message_to_send = '正在努力學習中~~'
                            elif radm == 4:
                                message_to_send = '是我的名字呦!'
                            elif radm == 5:
                                message_to_send = nickname + '~~'
                        elif msg == 'time':
                            message_to_send = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                        elif msg == 'date':
                            message_to_send = datetime.now().date().strftime("%Y-%m-%d")
                        else: #Can't recognize 無法辨識的話
                            radm = random.randint(1,15)
                            if radm > 13:
                                message_to_send = '小鸚鵡無言以對...'
                            elif radm > 9:
                                message_to_send = "ㄛ\n干我"
                            elif radm > 7:
                                message_to_send = message_text + "\n阿不就好棒棒?"
                            elif radm > 6:
                                message_to_send = "很酷ㄛ"
                            elif radm > 5:
                                message_to_send = "ㄛ好呦"
                            elif radm > 4:
                                message_to_send = message_text + "\nSounds good!"
                            else:
                                message_to_send = message_text
                    elif is_member_ed == False: #Not a member 非會員
                        if is_number(message_text):
                            if 32000>int(message_text)>10099:
                                tnfsh_class = message_text[0:3]
                                tnfsh_number = message_text[3:5]

                                new_record = dict()
                                new_record['tnfsh_class'] = tnfsh_class
                                new_record['tnfsh_number'] = tnfsh_number
                                new_record['fb_sender_id'] = sender_id
                                new_record['Created_time'] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                                new_record['PS'] = ''
                                new_record['nickname'] = tnfsh_class + tnfsh_number
                                new_record['Last_changed_time'] = 'None'
                                new_record['pss_win'] = "0"
                                new_record['pss_lose'] = "0"
                                new_record['pss_draw'] = "0"
                                try:
                                    info = user_info_query(sender_id)
                                    new_record['fb_name'] = info['name']
                                    new_record['fb_last_name'] = info['last_name']
                                    new_record['fb_first_name'] = info['first_name']
                                except:
                                    new_record['fb_name'] = ""
                                    new_record['fb_last_name'] = ''
                                    new_record['fb_first_name'] = ''
                                #Create new record 建立新資料
                                doc_ref = db.collection("user_info").document(sender_id)
                                doc_ref.set(new_record)
                                
                                #send a message first
                                message_to_send = '處理中...'
                                send_message(sender_id, message_to_send)
                                #Add to total_list
                                total_list_doc_ref = db.collection("total_list").document('total1')
                                total_docs = total_list_doc_ref.get()
                                fb_sender_id_list = format(total_docs.to_dict()['fb_sender_id_list'])
                                fb_sender_id_list_week1 = format(total_docs.to_dict()['fb_sender_id_list_week1'])
                                fb_sender_id_list_week2 = format(total_docs.to_dict()['fb_sender_id_list_week2'])
                                fb_sender_id_list_week3 = format(total_docs.to_dict()['fb_sender_id_list_week3'])
                                fb_sender_id_list_week4 = format(total_docs.to_dict()['fb_sender_id_list_week4'])
                                fb_sender_id_list_week5 = format(total_docs.to_dict()['fb_sender_id_list_week5'])
                                fb_sender_id_list_week6 = format(total_docs.to_dict()['fb_sender_id_list_week6'])
                                fb_sender_id_list_week7 = format(total_docs.to_dict()['fb_sender_id_list_week7'])

                                fb_sender_id_list += ','+sender_id
                                fb_sender_id_list_week1 += ','+sender_id
                                fb_sender_id_list_week2 += ','+sender_id
                                fb_sender_id_list_week3 += ','+sender_id
                                fb_sender_id_list_week4 += ','+sender_id
                                fb_sender_id_list_week5 += ','+sender_id
                                fb_sender_id_list_week6 += ','+sender_id
                                fb_sender_id_list_week7 += ','+sender_id

                                total_list_new_record = dict()
                                total_list_new_record['fb_sender_id_list'] = fb_sender_id_list
                                total_list_new_record['fb_sender_id_list_week1'] = fb_sender_id_list_week1
                                total_list_new_record['fb_sender_id_list_week2'] = fb_sender_id_list_week2
                                total_list_new_record['fb_sender_id_list_week3'] = fb_sender_id_list_week3
                                total_list_new_record['fb_sender_id_list_week4'] = fb_sender_id_list_week4
                                total_list_new_record['fb_sender_id_list_week5'] = fb_sender_id_list_week5
                                total_list_new_record['fb_sender_id_list_week6'] = fb_sender_id_list_week6
                                total_list_new_record['fb_sender_id_list_week7'] = fb_sender_id_list_week7
                                total_list_doc_ref.set(total_list_new_record)

                                message_to_send = tnfsh_class+tnfsh_number+'已完成綁定'
                                send_message(sender_id, message_to_send)
                                message_to_send = '輸入help取得說明'
                            else:
                                message_to_send = '您尚未綁定班級座號，請輸入您的班級座號共五位數(e.g.20101)'
                        else:
                            message_to_send = '您尚未綁定班級座號，請輸入您的班級座號共五位數(e.g.10101)'
                    else:
                        message_to_send = 'OuO'
                    try:
                        send_message(sender_id, message_to_send)
                    except:
                        send_message(sender_id, 'QAQ')
                if messaging_event.get("delivery"):  # delivery confirmation
                    pass
                if messaging_event.get("optin"):  # optin confirmation
                    pass
                if messaging_event.get("postback"):  # user clicked/tapped "postback" button in earlier message 透過按鈕非訊息框
                    #pass
                    #check if it is member
                    try:  #Check if it is a member, if true record its info
                        #log("search member")
                        sender_id = messaging_event['sender']['id']        # the facebook ID of the person sending you the message
                        recipient_id = messaging_event['recipient']['id']  # the recipient's ID, which should be your page's facebook ID                    
                        doc_ref = user_info_collection_ref.document(sender_id)
                        docs_dict = doc_ref.get().to_dict()
                        tnfsh_class = format(docs_dict['tnfsh_class'])
                        tnfsh_number = format(docs_dict['tnfsh_number'])
                        Created_time = format(docs_dict['Created_time'])
                        nickname = format(docs_dict['nickname'])
                        PS = format(docs_dict['PS'])
                        #print(docs)
                        #log(docs)
                        is_member_ed = True
                    except:  #Not a member
                        is_member_ed = False
                    payload = messaging_event['postback']['payload']
                    if (payload == 'get_started' and is_member_ed == False) or is_member_ed == False:
                        message_to_send = '請輸入班級座號以完成綁定\n(e.g.10101)'
                    else:
                        if payload == 'qw' or payload == '查詢本周' or payload == '查詢本週':
                            weekday = date.today().isoweekday()   
                            count_absent_total, count_late_total, count_leave_total = absent_query_period(tnfsh_class, tnfsh_number, (datetime.now() + timedelta(days = -weekday+1)).strftime("%Y-%m-%d"), datetime.now().date().strftime("%Y-%m-%d"))                            
                            message_to_send = '<您的本週缺席>\n'
                            if count_absent_total == 0:
                                message_to_send += '查無本週缺席\n'
                            else:
                                message_to_send += '本週共缺席'+str(count_absent_total)+'節\n'
                            if count_late_total > 0:
                                message_to_send += '本週共遲到'+str(count_late_total)+'節\n'
                            if count_leave_total > 0:
                                message_to_send += '本周共早退'+str(count_leave_total)+'節\n'
                            if count_absent_total + count_late_total + count_leave_total > 0:
                                message_to_send += '快去看看哪節課被記吧!\n'
                                message_to_send += shorten_url('https://sp.tnfsh.tn.edu.tw/attend/index.php/attend/search?begin='+(datetime.now() + timedelta(days = -weekday+1)).strftime("%Y-%m-%d")+'&end='+datetime.now().date().strftime("%Y-%m-%d")+'&class='+tnfsh_class+'&num='+tnfsh_number)
                        elif payload == 'q' or payload == '查詢最近':
                            date_today = datetime.now().date().strftime("%Y-%m-%d")
                            date_p1 = (datetime.now() + timedelta(days = -1)).strftime("%Y-%m-%d")
                            date_p2 = (datetime.now() + timedelta(days = -2)).strftime("%Y-%m-%d")
                            #Check today
                            count_absent_today, count_late_today, count_leave_today = absent_query(tnfsh_class, tnfsh_number, date_today)
                            #Check p1 day
                            count_absent_p1, count_late_p1, count_leave_p1 = absent_query(tnfsh_class, tnfsh_number, date_p1)
                            #Check p2 day
                            count_absent_p2, count_late_p2, count_leave_p2 = absent_query(tnfsh_class, tnfsh_number, date_p2)
                            #Deal message_to_send
                            message_to_send = '<您的最近缺席>\n'
                            if count_absent_today == 0:
                                message_to_send += '查無本日缺席\n'
                            else:
                                message_to_send += '你今天共缺席'+str(count_absent_today)+'節課\n'
                            if count_late_today > 0:
                                message_to_send += '你今天共遲到'+str(count_late_today)+'節課\n'
                            if count_leave_today > 0:
                                message_to_send += '你今天共早退'+str(count_leave_today)+'節課\n'
                            if count_absent_p1 == 0:
                                message_to_send += '查無昨天缺席\n'
                            else:
                                message_to_send += '你昨天共缺席'+str(count_absent_p1)+'節課\n'
                            if count_late_p1 > 0:
                                message_to_send += '你昨天共遲到'+str(count_late_p1)+'節課\n'
                            if count_leave_p1 >0:
                                message_to_send += '你昨天共早退'+str(count_leave_p1)+'節課\n'
                            if count_absent_p2 == 0:
                                message_to_send += '查無前天缺席\n'
                            else:
                                message_to_send += '你前天共缺席'+str(count_absent_p2)+'節課\n'
                            if count_late_p2 > 0:
                                message_to_send += '你前天共遲到'+str(count_late_p2)+'節課\n'
                            if count_leave_p2 > 0:
                                message_to_send += '你前天共早退'+str(count_leave_p2)+'節課\n'
                            if count_absent_today + count_late_today + count_leave_today + count_absent_p1 + count_late_p1 + count_leave_p1 + count_absent_p2 + count_late_p2 + count_leave_p2 >0 :
                                message_to_send += '快去看看哪節課被記吧!\n'
                                message_to_send += shorten_url('https://sp.tnfsh.tn.edu.tw/attend/index.php/attend/search?begin='+date_p2+'&end='+date_today+'&class='+tnfsh_class+'&num='+tnfsh_number)
                        elif payload == 'course': #我的課表按鈕
                            message_to_send = ""
                            send_image_message(sender_id, "https://tnfsh-absentee.web.app/courseTables/"+tnfsh_class+".jpeg")
                        elif payload == 'help' or is_member_ed == True:
                            message_to_send = '查詢近三日缺席: q 或 查詢最近\n查詢本周缺席: qw 或 查詢本週\n重設班級座號: c班級座號 (e.g. c10101)\n設定暱稱:ni+暱稱 (e.g. ni天堂)\n查詢個人設定:profile\n顯示課表:course'
                            send_message(sender_id,message_to_send)
                            message_to_send = '查詢指定區間: q+起始結束西元年月日\n(e.g. q2018010120190331)\n設定星期幾要推播晚安訊息:\nset+收推播的星期幾\n(e.g. 星期二四六日 set2467)'
                            send_message(sender_id, message_to_send)
                            message_to_send = '也可以跟我say hi ㄛ~~'
                            send_message(sender_id, message_to_send)
                            message_to_send = '像是1+1之類簡單的數學我其實也會算!\n想跟我玩遊戲的話就輸入gamehelp吧!'                   
                    send_message(sender_id, message_to_send)
    return "ok", 200

def send_to_all(message_text):
    total_list_doc_ref = db.collection('total_list').document('total1')
    total_docs = total_list_doc_ref.get()
    fb_sender_id_list = format(total_docs.to_dict()['fb_sender_id_list'])
    to_send_list = fb_sender_id_list.split(',')
    for recipient_id in to_send_list:
        send_message(recipient_id, message_text)

def send_message(recipient_id, message_text):

    log("sending message to {recipient}: {text}".format(recipient=recipient_id, text=message_text))

    params = {
        "access_token": os.environ["PAGE_ACCESS_TOKEN"]
    }
    headers = {
        "Content-Type": "application/json"
    }
    data = json.dumps({
        "recipient": {
            "id": recipient_id
        },
        "message": {
            "text": message_text
        }
    })
    r = requests.post("https://graph.facebook.com/v2.6/me/messages", params=params, headers=headers, data=data)
    if r.status_code != 200:
        print(r.status_code)
        print(r.text)
def send_image_message(recipient_id, image_url):

    log("sending message to {recipient}: {text}".format(recipient=recipient_id, text="send_image_message"))

    params = {
        "access_token": os.environ["PAGE_ACCESS_TOKEN"]
    }
    headers = {
        "Content-Type": "application/json"
    }
    data = json.dumps({
        "recipient": {
            "id": recipient_id
        },
        "message": {
            "attachment":{
                "type":"image", 
                "payload":{
                    "url": image_url, 
                    "is_reusable":True
      }
    }
        }
    })
    r = requests.post("https://graph.facebook.com/v2.6/me/messages", params=params, headers=headers, data=data)
    if r.status_code != 200:
        print(r.status_code)
        print(r.text)

def absent_query(tnfsh_class, tnfsh_number, day):  #Query single day
    url = 'https://sp.tnfsh.tn.edu.tw/attend/index.php/attend/search?begin='+day+'&end='+day+'&class='+tnfsh_class+'&num='+tnfsh_number
    html = urllib.request.urlopen(url).read()
    count_absent = str(html).count('btn-danger')
    count_late = str(html).count('btn-warning')
    count_leave = str(html).count('btn-info')
    return count_absent, count_late, count_leave    

def absent_query_period(tnfsh_class, tnfsh_number, str_day, end_day):  #Query a period
    url = 'https://sp.tnfsh.tn.edu.tw/attend/index.php/attend/search?begin='+str_day+'&end='+end_day+'&class='+tnfsh_class+'&num='+tnfsh_number
    html = urllib.request.urlopen(url).read()
    count_absent = str(html).count('btn-danger')
    count_late = str(html).count('btn-warning')
    count_leave = str(html).count('btn-info')
    return count_absent, count_late, count_leave    

def log(msg, *args, **kwargs):  # simple wrapper for logging to stdout on heroku
    try:
        if type(msg) is dict:
            msg = json.dumps(msg)
        else:
            #msg = 'sorry'
            msg = msg.format(*args, **kwargs)  #這裡改過!!原為unicode(msg).format~
        print(u"{}: {}".format(datetime.now(), msg))
    except UnicodeEncodeError:
        pass  # squash logging errors in case of non-ascii text
    sys.stdout.flush()

def is_number(s): #check if it is a interger
    try:
        int(s)
        return True
    except ValueError:
        pass
 
    try:
        import unicodedata
        unicodedata.numeric(s)
        return True
    except (TypeError, ValueError):
        pass
 
    return False

def shorten_url(longurl):
    s = pyshorteners.Shortener(Shorteners.TINYURL)
    shorturl = s.short(longurl)
    #Put your tinyurl info here 將tinyurl資訊放於此
    url_shortener = UrlShortener('TINYURL_Token', 'TINYURL_Name')
    shorten_url = url_shortener.get_short_link(shorturl)
    
    return shorten_url
def user_info_query(recipient_id):

    #log("sending btn message to all: ")

    params = {
        # Access Token from Facebook
        # Facebook提供之Access Token
        "access_token": 'ACCESS_TOKEN',
        "fields": "first_name,name,last_name,profile_pic"
    }
    headers = {
        "Content-Type": "application/json"
    }
    r = requests.get("https://graph.facebook.com/"+recipient_id, params=params, headers=headers)       
    if r.status_code != 200:
        print('於查詢'+recipient_id+'時出現錯誤:',end='')
        print(r.status_code)
        print(r.text)
    return r.json()

if __name__ == '__main__':
    app.run(debug=True)